# This is a basic workflow to help you get started with Actions

name: Deploy React.js

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:    
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Execute Deploy Webhook
      run: |
        sudo apt install -y curl ca-certificates
        curl -X POST http://34.193.104.186:9000/hooks/vet -H "X-Vet-Secret: 5dV4r7wKMWD2"
  deploy_frontend:
    env: 
      working-directory: "./frontend"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
      working-directory: ${{env.working-directory}}
    - name: Build
      run: npm run build
      working-directory: ${{env.working-directory}}
    - name: Deploy to s3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_S3_BUCKET: vet.lhei.org
        SOURCE_DIR: 'frontend/build'   # optional: defaults to entire repository
